version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
    environment:
      NODE_ENV: production
      ENV: ${ENV}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      PORT: ${PORT}
      GUILD_ID: ${GUILD_ID}
      CLIENT_ID: ${CLIENT_ID}
      FIREBASE_SERVICE_ACCOUNT: ${FIREBASE_SERVICE_ACCOUNT}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      CLERK_PUBLISHABLE_KEY: ${CLERK_PUBLISHABLE_KEY}
      LIMIT_REQUESTS: ${LIMIT_REQUESTS}
      MAX_REQ_TIME: ${MAX_REQ_TIME}
